VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "C_Lieferung"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public verladedatum As String
Public liefernummer As String
Public liefergruppe As String
Public versandstelle As String
Public beladung As String
Public ladedauer As Integer
Public ladebeginn As String
Public sap_meldung As String
Public cell_address As String
Public cell_address2 As String


